all:
  hosts:
    hyperv:
      ansible_host: 127.0.1.1
      ansible_connection: winrm
      ansible_winrm_transport: basic
      ansible_user: administrator
      ansible_password: P@ssword1234!
      ansible_winrm_server_cert_validation: ignore
      ansible_become_method: runas
      ansible_become_user: administrator
      ansible_become_password: P@ssword1234!
  children:
    kube:
      children:
        master:
          hosts:
            k8smaster:
              ansible_host: 192.168.1.235
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_become_password: vagrant
        nodes:
          hosts:
            k8snode1:
              ansible_host: 192.168.1.234
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_become_password: vagrant
            k8snode2:
              ansible_host: 192.168.1.236
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_become_password: vagrant