all:
  hosts:
    hyperv:
      ansible_host: 172.20.10.4
  children:
    kube:
      children:
        master:
          hosts:
            k8smaster:
              ansible_host: 192.168.1.235
        nodes:
          hosts:
            k8snode1:
              ansible_host: 192.168.1.234
            k8snode2:
              ansible_host: 192.168.1.236
