all:
  children:
    kube:
      children:
        master:
          hosts:
            k8smaster:
              ansible_host: 192.168.1.235
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_become_password: vagrant
        nodes:
          hosts:
            k8snode1:
              ansible_host: 192.168.1.234
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_become_password: vagrant
            k8snode2:
              ansible_host: 192.168.1.236
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_become_password: vagrant