
- name: Ensure Hyper V is installed
  win_feature: 
    name: Hyper-V
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: "Adding xHyperV module using DSC"
  win_psmodule:
    name: xHyper-V
    state: present
  become: True