- name: "Create folder for packer files"
  win_file:
    path: '{{ root }}\\packer'
    state: directory
    force: no
  vars:
    root: "c:\\Kubernetes"

- name: "copy files & folders"
  win_copy:
    src: '{{role_path}}/files/packer/'
    dest: '{{ root }}\\packer'
  vars:
    root: "c:\\Kubernetes"

- name: "Check if image exists"
  win_stat:
    path: "{{ output_dir }}\\Virtual Hard Disks\\ubuntu-bionic.vhdx"
  register: stat_image
  vars:
    hyperv_switch: "packer-hyperv-iso"
    username: "etienne"
    password: "P@ssword1234!"
    output_dir: "{{ root }}\\Source_vhdx"
    root: "c:\\Kubernetes"

- name: "Packer - validate server image"
  win_command: "packer validate -var 'hyperv_switchname={{ hyperv_switch }}' -var 'username={{ username }}' -var 'password={{ password }}' -var 'output_dir={{ output_dir }}' .\\hyperv-ubuntu-18.04.json"
  args:
    chdir: "{{ root }}\\packer"
  retries: 2
  delay: 60
  become: True
  when: stat_image.stat.exists == false
  vars:
    hyperv_switch: "packer-hyperv-iso"
    username: "etienne"
    password: "P@ssword1234!"
    output_dir: '{{ root }}\Source_vhdx\'
    root: "c:\\Kubernetes"
  tags:
    - skip_ansible_lint

- name: "Packer - build server image"
  win_command: "packer -machine-readable build -force -var 'hyperv_switchname={{ hyperv_switch }}' -var 'username={{ username }}' -var 'password={{ password }}' -var 'output_dir={{ output_dir }}' .\\hyperv-ubuntu-18.04.json"
  args:
    chdir: "{{ root }}\\packer"
  retries: 2
  delay: 60
  become: True
  when: stat_image.stat.exists == false
  vars:
    hyperv_switch: "packer-hyperv-iso"
    username: "etienne"
    password: "P@ssword1234!"
    output_dir: '{{ root }}\Source_vhdx\'
    root: "c:\\Kubernetes"
  tags:
    - skip_ansible_lint
