- hosts: hyperv
  tasks:

    - name: "Check if image exists"
      win_stat:
        path: "C:\\Users\\Administrator\\Documents\\git\\webcast\\part1\\packer\\output-hyperv-iso\\Virtual Hard Disks\\ubuntu-bionic.vhdx"
      register: stat_image


    - name: "Packer - validate server image"
      win_command: packer validate .\hyperv-ubuntu-18.04.json
      args:
        chdir: 'C:\\Users\\Administrator\\Documents\\git\\webcast\\part1\\packer\\'
      retries: 2
      delay: 60
      become: True
      when: stat_image.stat.exists == False
      tags:
        - skip_ansible_lint

    - name: "Packer - build server image"
      win_command: packer -machine-readable build -force .\hyperv-ubuntu-18.04.json
      args:
        chdir: 'C:\\Users\\Administrator\\Documents\\git\\webcast\\part1\\packer\\'
      retries: 2
      delay: 60
      become: True
      when: stat_image.stat.exists == False
      tags:
        - skip_ansible_lint
