- hosts: hyperv
  tasks:
    - name: "Packer - validate server image"
      win_command: packer validate .\hyperv-ubuntu-18.04.json 
      args:
        chdir: 'C:\\Users\\Administrator\\Documents\\git\\webcast\\part1\\packer\\'
      retries: 2
      delay: 60
      become: True

    - name: "Packer - build server image"
      win_command: packer -machine-readable build -force .\hyperv-ubuntu-18.04.json
      args:
        chdir: 'C:\\Users\\Administrator\\Documents\\git\\webcast\\part1\\packer\\'
      retries: 2
      delay: 60
      become: True

    - name: "Adding xHyperV module using DSC"
      win_psmodule:
        name: xHyper-V
        state: present
      become: True

    - name: "create folders"
      win_file:
        path: "C:\\Kubernetes\\{{ item }}"
        state: directory
      with_items:
        - master
        - worker01
        - worker02

    - name: "copy vhd in folders"
      win_copy:
        src: "C:\\Users\\Administrator\\Documents\\git\\webcast\\part1\\packer\\output-hyperv-iso\\Virtual Hard Disks\\ubuntu-bionic.vhdx"
        dest: "c:\\Kubernetes\\{{ item }}\\{{ item }}.vhdx"
        remote_src: yes
      with_items:
        - master
        - worker01
        - worker02

    - name: "Launch dsc configuration script"
      win_shell: C:\Users\Administrator\Documents\git\webcast\part1\dsc\config_vm.ps1
      become: true
    
    - name: "Retrieving IP of each vm"
      win_shell: Get-VMNetworkAdapter -VMName * | ConvertTo-Json
      register: vms
      become: true
    
    - set_fact:
        jsonvms: "{{ vms.stdout | from_json }}"

    
    
    - name: "Grab ipv4 only"
      set_fact:
        vmiplist: "{{ jsonvms | json_query(filter) }}"
      vars:
        filter: >-
          [].IPAddresses
    
    - name: "Debug"
      debug:
        msg: "{{ item[0] }}"
      with_items:
        - "{{ vmiplist }}"
    
    - name: "Add Host to inventory"
      add_host:
        name: "k8s_master"
        groups: kube,master
        ansible_host: "{{ vmiplist[0][0] }}"
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_become_user: vagrant
        ansible_become_pass: vagrant
      delegate_to: localhost

    - name: "Add Host to inventory"
      add_host:
        name: "k8s_node1"
        groups: kube,node
        ansible_host: "{{ vmiplist[1][0] }}"
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_become_user: vagrant
        ansible_become_pass: vagrant
      delegate_to: localhost

    - name: "Add Host to inventory"
      add_host:
        name: "k8s_node2"
        groups: kube,node
        ansible_host: "{{ vmiplist[2][0] }}"
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_become_user: vagrant
        ansible_become_pass: vagrant
      delegate_to: localhost

- hosts: kube
  become: yes
  tasks:
    - name: Install prerequisites
      apt: 
        name: ['apt-transport-https', 'curl', 'software-properties-common', 'ca-certificates']
        state: present
      become: yes
    - name: Add Apt signing key for Kubernetes repo from Google
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      become: True
    - name: Add Apt signing key for docker repo
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: True
    - name: Add an Apt repository for docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: docker
      become: True
    - name: Add an Apt repository for kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes
      become: True
    - name: Install stuff
      apt: 
        name: ['kubelet', 'kubeadm', 'kubectl', 'docker-ce']
        state: present
        update_cache: yes
      become: True