- name: "create folders"
  win_file:
    path: "{{ root }}\\{{ item }}"
    state: directory
    force: no
  with_items:
    - master
    - worker01
    - worker02
  vars:
    root: "c:\\Kubernetes"

- name: "copy dsc script"
  win_copy:
    src: '{{role_path}}/files/config_vm.ps1'
    dest: '{{ root }}\\config_vm.ps1'
    force: yes
  vars:
    root: "c:\\Kubernetes"

- name: "copy vhd in folders"
  win_copy:
    src: "{{ output_dir }}\\Virtual Hard Disks\\ubuntu-bionic.vhdx"
    dest: "{{ root }}\\{{ item }}\\{{ item }}.vhdx"
    remote_src: yes
    force: no
  with_items:
    - master
    - worker01
    - worker02
  vars:
    hyperv_switch: "packer-hyperv-iso"
    username: "etienne"
    password: "P@ssword1234!"
    output_dir: "{{ root }}\\Source_vhdx"
    root: "c:\\Kubernetes"

- name: "Launch dsc configuration script"
  win_shell: ".\\config_vm.ps1 -vmswitch {{ hyperv_switch}} -rootpath {{ root }}"
  become:
  args:
    chdir: "{{ root }}"
  vars:
    hyperv_switch: "packer-hyperv-iso"
    username: "etienne"
    password: "P@ssword1234!"
    output_dir: "{{ root }}\\Source_vhdx"
    root: "c:\\Kubernetes"
  tags:
    - skip_ansible_lint
