- name: Install packer
  win_chocolatey:
    name: packer
    state: present

- name: Set an environment variable for all users
  win_environment:
    state: present
    name: PACKER_LOG
    value: 1
    level: machine


- name: Set an environment variable for all users
  win_environment:
    state: present
    name: PACKER_LOG_PATH
    value: packerlog.txt
    level: machine

- name: "Create folder for packer files"
  win_file:
    path: '{{ root }}\\packer'
    state: directory
    force: no

- name: "copy files & folders"
  win_copy:
    src: "{{role_path}}/files/packer/"
    dest: '{{ root }}\\packer'
    force: yes

- name: "Check if image exists"
  win_stat:
    path: "{{ output_dir }}\\Virtual Hard Disks\\ubuntu-bionic.vhdx"
  register: stat_image

- name: "Packer - validate server image"
  win_command: "packer validate -var 'hyperv_switchname={{ hyperv_switch }}' -var 'username={{ username }}' -var 'password={{ password }}' -var 'output_dir={{ output_dir }}' .\\hyperv-ubuntu-18.04.json"
  args:
    chdir: "{{ root }}\\packer"
  retries: 2
  delay: 60
  become: True
  when: stat_image.stat.exists == false
  tags:
    - skip_ansible_lint

- name: "Packer - build server image"
  win_command: "packer -machine-readable build -force -var 'hyperv_switchname={{ hyperv_switch }}' -var 'username={{ username }}' -var 'password={{ password }}' -var 'output_dir={{ output_dir }}' .\\hyperv-ubuntu-18.04.json"
  args:
    chdir: "{{ root }}\\packer"
  retries: 2
  delay: 60
  become: True
  when: stat_image.stat.exists == false
  tags:
    - skip_ansible_lint
